preprocess:
  detection: clahe
  recognition: clahe
  clahe:
    clipLimit: 2.0
    tileGridSize: [8, 8]
debug:
  output: debug
  draw_max_loc: true
  draw_boxes: true
  draw_num_roi: true
  draw_date_roi: true
  save_chips: true
